name: Codacy Security Scan

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  codacy-security-scan:
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Codacy Analysis CLI
        uses: codacy/codacy-analysis-cli-action@v4
        with:
          # Produces SARIF for GitHub code scanning
          output: results.sarif
          format: sarif
          # Severity of non-security issues for GH compatibility
          gh-code-scanning-compat: true
          # Forces 0 exit code to ensure SARIF is always uploaded;
          # GitHub will decide PR status based on the uploaded alerts.
          max-allowed-issues: 2147483647

      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarifsss
