name: Codacy Security Scan

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  codacy-security-scan:
    name: Codacy Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Codacy Analysis CLI (Semgrep only)
        uses: codacy/codacy-analysis-cli-action@v4
        with:
          tool: semgrep

          # Produces SARIF for GitHub code scanning
          output: results.sarif
          format: sarif
          gh-code-scanning-compat: true

          # Don’ts fail the job due to findings (we still want SARIF uploaded)
          max-allowed-issues: 2147483647

      - name: Upload SARIF results file
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: results.sarif
